owner: dreamingg
repo: status

sites:
  - name: Eddie - Chicago, USA - Ryzen 9 3900x
    url: $EDDIE_IP
    port: $TCP_PING_PORT
    check: "tcp-ping"
  - name: Alex - London, UK - Ryzen 5 5600x
    url: $ALEX_IP
    port: $TCP_PING_PORT
    check: "tcp-ping"
  - name: Game Server Panel (USA)
    url: $GSP_URL
  - name: Proxy Management Panel (USA)
    url: $PRXY_URL
  - name: Teleport (USA)
    url: $TP_URL

status-website:
  cname: status.dreamin.dev
  theme: dark
  logoUrl: https://avatars.githubusercontent.com/u/64283475
  name: Dreamin.gg Uptime Status
  introTitle: ""
  introMessage: "Dreamin.gg uptime monitoring, see if our servers are online!"
  navbar:
    - title: Home
      href: https://dreamin.gg
    - title: Status
      href: /

# See https://upptime.js.org/docs/configuration
